# Site settings
title: Madis Nõmme's web page
description: I help data driven small online businesses increase profits by using external data sources combined with machine learning
positioning:
  - I help data driven small online businesses increase profits by using information from external sources more efficiently.
  - Unlike many other software consultants I can deliver a solution taylored specifically to your case faster because of my experience.
url: 'https://mad.is'
baseurl: '/'
google_analytics: 'UA-53654616-1'
disqus_shortname: 'blogmadis'
social:
  name: Madis Nõmme
  links:
    - https://github.com/madis
    - https://www.linkedin.com/in/madisnomme
    - https://twitter.com/MadisIT

author:
  name: 'Madis Nõmme'
  email: contact@mad.is
  twitter: madisIT
  picture: /images/profile.png

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  span:
    line_numbers: false
  block:
    line_numbers: true
    start_line: 1

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
