# Site settings
title: Madis Nõmme
description: 'Hackerman extraordinaire specializing on backend development (Ruby, Clojure) and communications (WebRTC, Twilio). Writing on coding, electronics and more'
url: 'https://blog.mad.is'
baseurl: '/'
google_analytics: 'UA-53654616-1'
disqus_shortname: 'blogmadis'

author:
  name: 'Madis Nõmme'
  email: contact@mad.is
  twitter_username: madis_nomme
  github_username:  madis
  linkedin_username:  madisnomme

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
